export const ROLES = {
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE',
};

export const ACCOUNT_STATUS = {
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
};

export const EMPLOYMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  TERMINATED: 'TERMINATED',
  ON_LEAVE: 'ON_LEAVE',
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  LEAVE: 'LEAVE',
};

export const LEAVE_TYPE = {
  PAID: 'PAID',
  SICK: 'SICK',
  UNPAID: 'UNPAID',
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const DOCUMENT_TYPE = {
  RESUME: 'RESUME',
  ID_PROOF: 'ID_PROOF',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  EDUCATIONAL_CERTIFICATE: 'EDUCATIONAL_CERTIFICATE',
  EXPERIENCE_LETTER: 'EXPERIENCE_LETTER',
  OFFER_LETTER: 'OFFER_LETTER',
  CONTRACT: 'CONTRACT',
  OTHER: 'OTHER',
};

export const GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
};
